### ISSUE TITLE
Won't save username and password

### ISSUE THREAD

**Issue by GervaisdeM** [grantmcwilliams/PlexForBoxee#13]
Love this pleXee app
:+1: 

* Downloaded the software via the repository method
* Launch the app on my boxee
* Doesn't find my server by discovery
 * put my Plex username and password in
 * click save
 * works fine
* Exit Plexee App

* Relaunch Plexee
* Doesn't find my server by discovery
 * put my Plex username and password in
 * click save
 * works fine
* Exit Plexee App
:(

It's just not saving my credentials between launches...

I am running:
* BOXEE+HACKS. It is at version 1.4.6 and tells me that there are no updates.
* Boxee firmware 1.5.1.23735-b6a5be1
* Plexee v1.10
* Plex Server v 0.9.11.4

Let me know if you would like any more information and/or if you would like me to test something for you.

**Comment by GervaisdeM** [comment]
@jinxo13 Thanks for the info on where the config file needs to be. I telnet'd into my boxee and manually wrote the registry.xml file. Problem solved.

**Comment by tcough** [comment]
hi jinxo13 / GervaisdeM - 

i just started a separate issue directed to grantmcwilliams but maybe one of you can help me out.  can you tell me exactly what i need to type in telnet to update the registry.xml file?  i am completely new to Telnet and have no idea of what commands to use, etc...  i did the touch registry.xml file so it's there now, but i don't know how to edit the save the file in Telnet.  any help would be appreciated.  thanks

**Comment by grantmcwilliams** [comment]
I haven't done this so perhaps one of the people who have can comment.

Grant McWilliams
http://grantmcwilliams.com/

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

**Comment by GervaisdeM** [comment]
Hi tcough,

This was a long time ago for me and my Boxee is sitting in a Cupboard right now. If you are aksing how to telnet, then this depends on your OS. If you are running Windows, then I do not know what is a good telnet client. On a Mac or Linux, you open a terminal and type:
```
telnet IP-ADDRESS-OF-YOUR-BOXEE
```
I can't remember the default login credentials... Hopefully, you know them

As for editing a file on the command line, I use vi or vim:
```
vi /data/.boxee/UserData/profiles//apps/plexee.plexforboxee/registry.xml
```

You then hit "i" to be in insert mode. You should be able to edit the file as you would expect by moving to the correct lines and making your changes. When you are ready to save the file, you hit "ESC" to exit insert mode and then type ":wq" (write and quit).

You could also try nano (if it is on there and you are not used to command line text editors, then you might like nano better)
```
nano /data/.boxee/UserData/profiles//apps/plexee.plexforboxee/registry.xml
```

There are commands listed at the bottom of the nano screen that shows you how to exit, etc.

Hope this helps.

Cheers,
Gervais

**Comment by InsaneSplash** [comment]
Hello,

Would you know what the xml ID would be to set the manual server to enabled and the username/password to enabled?

It seems that the app does not write to the registry.xml file to save settings. I modified the file permissions and directory, but no luck.

Would your app in the future support local users on a local plex server?
