### ISSUE TITLE
Support for multiple audio streams?

### ISSUE THREAD

**Issue by ulrikL** [grantmcwilliams/PlexForBoxee#15]
Hi

It would be avery nice feature to add support for multiple audio streams.

Best regards

**Comment by jinxo13** [comment]
Hi ulrikL,

Thanks for the request - I'm planning to include this into the current changes I'm working on at the moment.

I have it working but it does introduce some annoying limitations that I'm working through. Mainly as the Boxee API's don't allow switching the audio stream (and the standard Player ability doesn't work for non-local media), so Plex has to do this - but this remuxes the media stream - and Boxee can no longer seek back and forward.

It's not the end of the world - and you can play the default then use stop - switch audio and use resume to get to a position - but still annoying.

Alternately an additional solution I might explore is if you have a remote mount to the media library then Boxee treats this as a local file and the standard Boxee player functionality to switch audio/subtitles should work. But this won't work for everyone.

Any comments welcome!

Cheers,
Hamish

**Comment by jinxo13** [comment]
Hi ulrikL,

The latest release now supports multiple audio streams.

Cheers,
Hamish

**Comment by ulrikL** [comment]
Wonderful news! I'll try it out this weekend and take a look at the code as
well.

Br

**Comment by jinxo13** [comment]
Great just note that the latest release is not available via the
repository, as Grant has found that the app signing from http://boxee.tv is
not working.

The details for how to install will be updated soon on the main git page.
Install Option 2 is recommended.
https://github.com/grantmcwilliams/PlexForBoxee

Cheers,
Hamish


Hamish McNeish
Ph: +61-(0)2-86047229
Mobile: +61-(0)4-27047058
