### ISSUE TITLE
Jan-2015 - Any feature requests? - for next release

### ISSUE THREAD

**Issue by jinxo13** [grantmcwilliams/PlexForBoxee#16]
Hi all,

Happy new year!
I currently have some holiday time from work - yipee! So I've been working on some new features.

I'd like to hear if there are any small changes/tweaks - or features that you'd like. Or comments on what I have done below. If I get time I'll add screen shots to the wiki for feedback.

So far I have completed:

Features:
- Dialog to **confirm exit** from Plexee
- **Refresh** button on the home screen
- **Search** button on the home screen allows searching across shows/movies/episodes/albums or actors or tracks (shows results on home screen)
- Basic **support for music**
  - added a player at top of screens (the remote play/pause button works on this)
  - changed album to list tracks with time etc...
- Show **myPlex Queue** (on home screen)
- Support to **play different media versions** Plex has for the same movie
- Support **alternate audio streams** - with some limitations at present :(

Tweaks:
- Enhancement to determine the local server address when using myPlex

Fixed Bugs:
- Updating progress not working if connected just by myPlex (It looks like this wouldn't work)
- Fix for channels not playing

----

I'd like to also add:
- Support for Plex playlists
- Support queuing music tracks

Cheers,
Hamish

**Comment by jonlbauer** [comment]
So cool that you guys are continuing to work on this!

Is it possible to get theme music support?

- Jon

**Comment by grantmcwilliams** [comment]
MyPlex Queue is at the top of my list. Most of the other features you've listed are also nice. Keep up the good work.

**Comment by jinxo13** [comment]
Hi all,

I've - at long last - released these changes.
All the items above were added - and I managed to solve the alternate audio stream limitations.

Cheers,
Hamish
