### ISSUE TITLE
How to install v1.11 via Telnet?

### ISSUE THREAD

**Issue by tcough** [grantmcwilliams/PlexForBoxee#19]
Hi grantmcwilliams - I'm actually facing two challenges and i was hoping you could help me out.  

1) I already installed V1.10 but I'm running into the "Won't save username and password" issue that was already reported before.  I'm a noob and not very efficient at using Telnet.  I can get the registry file created through the "touch" command, but I don't know how to actually get the code in there now.  can you tell me what i need to do exactly in telnet please?

2) As a way to get around this first issue, i wanted to try loading V1.11 of plexee; still stuck in Telnet though as I don't know how to extract the zip file into apps.  Can you provide specific instructions for how to do this too?  

thanks in advance!

**Comment by InsaneSplash** [comment]
Hello.

An easy way is to create the registry.xml file locally and then ftp it up to the BoxeeBox.

Paste:

```
<registry>
<value id="discoverTime">1</value>
<value id="discovertime">1</value>
<value id="manualhost"><IP ADDRESS></value>
<value id="manualport">32400</value>
<value id="myplexpassword"><PASSWORD></value>
<value id="myplexusername"><USERNAME></value>
<value id="usemyplex">True</value>
</registry>
```

Upload the file to : /data/.boxee/UserData/profiles/<USERNAME>/apps/plexee.plexforboxee

**Comment by grantmcwilliams** [comment]
Thanks for the response InsaneSplash. I'm afraid my development came to a screeching halt when Boxee/Samsung broke the package signing server and then never fixed it. Without the ability for me to fix bugs and create distributed packages effectively I haven't spent a lot of time on this. 

What needs to happen is for me to change the instructions on how to manually install the plexforboxee package in a detailed way. Maybe we already have that but I haven't done it.

**Comment by InsaneSplash** [comment]
No Problem! Its a pity that the whole boxeebox/samsung saga went that way, but maybe one day in the future one of us will put together a howto around manually installing your cool app for boxeebox. :+1:

**Comment by grantmcwilliams** [comment]
Actually I'm battling it right now, I may very well be able to sign apps again. It's a bit flakey but we may be back in business.

**Comment by grantmcwilliams** [comment]
I managed to get version 1.11 signed and uploaded. I just rebooted my BoxeeBox and it installed fine. I've also updated the Readme and added installation and troubleshooting pages.

**Comment by InsaneSplash** [comment]
Awesome!! Well Done! Do I hear a version 1.12 in the distance. Let me know if you need any help. Would like to test the auth so you don't have to run discovery. With family mode it doesn't work unfortunately.

Could it be the requirement to support ssl/tls?

**Comment by grantmcwilliams** [comment]
I'm not sure what the current status is. Not being able to sign the apps stopped a lot of people from updating. I'm not sure if Hamish even has a working BoxeeBox at this point.

What needs to be done with auth? I've been using this since version 1.0 so I've not had to reset anything. Please advise.

**Comment by InsaneSplash** [comment]
Ok, cool.

With the updates being rolled out with Plex media server, it now supports encrypted connections. 

Plex also supports something called family mode which allows one to have multiple local users with their own viewing profiles and restrictions.

Besides the config file not being updated with saved settings, my experience has been that if you enable the local auth and disable the open  content viewing through gdm, it displays no content.

I've tried to use the auth and local server options with and without discovery but the only way I could see content was using the gdm anonymous method.

**Comment by jinxo13** [comment]
Great job Grant. I will dust my BoxeeBox off and see if it still works - and have a look at the local user options.

**Comment by jinxo13** [comment]
Hi InsaneSplash,

The saved settings seems to be a common issue for some - but not one I've been able to replicate so far. I recall the debug logs weren't helpful from past cases. But if you can check if there are any errors that would be good.
The only other thought I have here is to stop using the underlying Boxee config API - where I suspect the problem is - and use a custom one to access the config file.

I've done the hard part (I hope) and have mine working with multiple users (no user screen yet though) - but I haven't changed the other security options.

On the security settings can you let me know exactly what server settings you changed - to make sure I test these. I'm planning to test changing "Secure connections" to required and trying with GDM on and GDM off. I'm not planning to try and test certificates. Does this cover it?

I note that the switched user will be persisted in the config file.

Cheers,
Hamish

**Comment by jinxo13** [comment]
Hi all,

I've just completed the changes to support the latest features.
I've also had a go at dealing with the settings not being saved. But I don't know the actual issue so it may or may not help.
It should support multiple users (no pins requested on switch though) and secured servers.

Please test it out and let me know if it solves the issues - and any comments.
If you have an issue the log messages reported in the boxee log file will help a lot.

Cheers,
Hamish

**Comment by InsaneSplash** [comment]
Hi,

This is great news! Do you have any recommendations on installing this
update or could one just download the latest git zip and overwrite the old
app?

Will the repo be updated in the future?

Cheers!

--
Kind Regards
Richard

**Comment by grantmcwilliams** [comment]
My plan is for it to be available later today.

Grant McWilliams
http://grantmcwilliams.com/

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

**Comment by InsaneSplash** [comment]
Ok perfect.

I tried a simple overwrite of my current install with the new source, but
when running the app it complains about validation. Will wait for the
official release of 1.12 :)


--
Kind Regards

Richard Mayhew

**Comment by jinxo13** [comment]
In case your looking to do this manually again - it takes a few steps to get a manual working.
Here's what I've done:

1. Add the test-app settings back into the descriptor.xml file
&lt;test-app&gt;true&lt;/test-app&gt;

2. You need to follow the steps at the url below - provides a developer key:
http://bbx.boxee.tv/developer

3. I copy both the plexee.pleforboxee folder and the developer key file onto an SD card under /BoxeeApps

4. Remove the current installed Plexee
You may be able to do it from the Plex GUI.
I do it manually
rm -rf /data/.boxee/UserData/apps/plexee.plexforboxee
rm -rf /data/.boxee/UserData/profiles/xxxx/apps/plexee.plexforboxee

Where xxxx = your boxee username

**Comment by grantmcwilliams** [comment]
I just created a version 1.12 package to the repository. I haven't had the time to test is and won't before tomorrow but please let me know if there are any issues.

**Comment by grantmcwilliams** [comment]
I've updated the wiki to include the manual instructions above.

**Comment by tcough** [comment]
V1.12 works like a charm!
