### ISSUE TITLE
All mkv files isn't working. 

### ISSUE THREAD

**Issue by raskirill** [grantmcwilliams/PlexForBoxee#24]
In new version 1.12 all mkv files on my local plex media server isn't working at all. When I choose a film in list the movie page isn't opening. In previous version everything was fine. Checked settings,  there is nothing that can help.
Any suggestions?

**Comment by BakaNode** [comment]
I also have this issue. I didn't personally test every single MKV but about 4-5 different types all failed to do anything at all. No error or useful info. I push the select button to confirm my choice and I get the confirm noise but no result.

**Comment by grantmcwilliams** [comment]
Hmm, we'll look into it. I didn't think anything would have changed in that
department but obviously it has..

Grant McWilliams
http://grantmcwilliams.com/

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

**Comment by grantmcwilliams** [comment]
I don't see anything in PlexForBoxee that has anything to do with metroska files at all. Did you update your plexmediaserver recently?

**Comment by molten360** [comment]
Plex Server went thru a major update a week or two ago.

**Comment by raskirill** [comment]
Last version, no updates are available...

**Comment by jinxo13** [comment]
Hi all,
I'll be able to have a look at the weekend (in 3 days).
I have a new release which fixes a couple of multi-user problems.
I'll test mkv's on this as well.
Cheers,
Hamish

**Comment by grantmcwilliams** [comment]
I've created packages for release 1.13. Please test them out and let me know.

**Comment by jinxo13** [comment]
I think this can be closed.
