### ISSUE TITLE
Option 2 - Manual install from repository - no directory

### ISSUE THREAD

**Issue by nonstop99** [grantmcwilliams/PlexForBoxee#26]
I tried to install this from the zip

I have boxee hacks installed but I don't have the correct folder...

I have

/data/lost+found
/data/etc..
/data/hack..
/data/hack/boxee
/data/hack/boxee/scripts
/data/plugins

but I don't have..

/data/.boxee/UserData/apps 

I have the app installed from the repository but I noticed the grantwilliams website was down the other day so I couldn't run it

**Comment by grantmcwilliams** [comment]
It's back up. I had a drive failure. It should all be functional but I just
got it back up so I haven't tested everything.

Grant McWilliams
http://grantmcwilliams.com/

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

**Comment by nonstop99** [comment]
yep it's all working again :)

but I wondered if there was a better way to not depend on the website so much?

**Comment by grantmcwilliams** [comment]
Depends on if you like pain or not. The easiest way by far to install the app is just by adding the repository. No matter how we serve the app either we're putting it on a server on the Internet and you're manually installing it or we're creating the repository. Either way we still need a place to put it. 

The server has only been down for maybe 2 days in the last couple of years.  A much bigger issue is that at some point I'll no longer be able to sign the app turning our Boxee boxes into door stops. We had that scare not that long ago when someone at Samsung leaned on the signing server's power button.

**Comment by nonstop99** [comment]
ah i'll leave it as it is :) I don't like pain :)

**Comment by nonstop99** [comment]
Hi Grant,

It looks like the server is down again?

kind regards

**Comment by grantmcwilliams** [comment]
It's up. However, we're in the middle of an "unprecedented storm" and we
had a 30 second blackout. I imaging networking equipment is coming back up.

Grant McWilliams
http://grantmcwilliams.com/

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

**Comment by nonstop99** [comment]
yep its working again!

stay safe in the storm!

**Comment by jinxo13** [comment]
I think this issue can be closed.

**Comment by grantmcwilliams** [comment]
Thanks!  I haven't had access to a Boxee for about 18 months now. It saddens me but they'll probably all end up in garage sales at some point. I really wanted Samsung to release the ability to sign packages or an easy way of turning it off.
