### ISSUE TITLE
App will not display

### ISSUE THREAD

**Issue by FSFan** [grantmcwilliams/PlexForBoxee#28]
Don't know if this is a "dead" app or not but I'm attempting to install it on my Boxeebox.  The repository does not work so I am using the manual method.  Installing to the correct directory (.boxee one) under plexee.plexeeforboxee and it doesn't show up.  Ideas?  Thanx!

-Rick

**Comment by grantmcwilliams** [comment]
Rick,
   Try different versions, I can't sign apps anymore so I can't make new ones. This app was working in the past but I don't currently have a Boxee Box accessible to test as it's been stored for now. 

If you want to manually load an old one here's the directory - http://grantmcwilliams.com/plexforboxee/download/  

All versions up to 1.13 were working fine.

**Comment by FSFan** [comment]
yes, I seen the info about the signature.  I went all the way back to v1.10 and no joy, so it must be a problem on my end.  Thanx for the help tho.  Have a good day

-Rick

**Comment by grantmcwilliams** [comment]
It makes me wonder if something didn't happen to the checksums of the apps.
I moved to a new server a couple of months ago. I have access to the old
files. It makes no sense why all versions stopped working. I'll check on it.

**Comment by FSFan** [comment]
Just wondering if you have found out anything?  Thanx!

-Rick

**Comment by jinxo13** [comment]
See the latest manual install instructions.
Likely the test-app setting was missing.
